export interface LegalCase {
  id: string;
  title: string;
  facts: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  eli5: string;
  category: "criminal" | "contract" | "tort" | "constitutional";
  difficulty: "easy" | "medium" | "hard";
  rarity: "common" | "rare" | "legendary";
  principle: string;
}

export const STATIC_CASES: LegalCase[] = [
  // ─── EASY CONTRACT ───────────────────────────────────────────────────────────
  {
    id: "c001",
    title: "The Unpaid Contractor",
    facts: "Marcus agreed to renovate a client's kitchen for $8,000. He completed 90% of the work but was denied access to finish. The client refused to pay anything.",
    question: "Is Marcus entitled to payment?",
    options: ["No, the contract was not fully performed", "Yes, under quantum meruit for work done", "Only if he sues in criminal court", "No, because the client owns the property"],
    correctIndex: 1,
    explanation: "Under quantum meruit, Marcus can recover reasonable value for services rendered. A party cannot unjustly benefit from another's partial performance.",
    eli5: "Marcus did most of the work, so it's only fair he gets paid — you can't eat someone's cooking and then say you won't pay because they didn't wash the dishes.",
    category: "contract", difficulty: "easy", rarity: "common",
    principle: "Quantum meruit — reasonable value for partial performance",
  },
  // ─── EASY CRIMINAL ───────────────────────────────────────────────────────────
  {
    id: "c002",
    title: "The Midnight Assault",
    facts: "Deron was struck from behind by a stranger who then stole his phone. The attacker was caught on CCTV.",
    question: "What is the primary criminal charge?",
    options: ["Theft only", "Assault and robbery", "Trespass to person", "Breach of the peace"],
    correctIndex: 1,
    explanation: "Using force in the course of stealing constitutes robbery — more serious than simple theft or assault alone.",
    eli5: "Hitting someone AND taking their stuff is two crimes at once — that's robbery, which is worse than just stealing.",
    category: "criminal", difficulty: "easy", rarity: "common",
    principle: "Robbery — theft accompanied by force or threat of force",
  },
  // ─── EASY TORT ───────────────────────────────────────────────────────────────
  {
    id: "c003",
    title: "The Slippery Supermarket",
    facts: "Priya slipped on an unmarked wet floor and fractured her wrist. Staff were notified of the spill 45 minutes earlier but took no action.",
    question: "Can Priya successfully sue the supermarket?",
    options: ["No, she should have been more careful", "Yes, for negligence — duty of care breached", "Only if she wore unsafe shoes", "No, supermarkets cannot be sued"],
    correctIndex: 1,
    explanation: "The supermarket owed Priya a duty of care as a visitor. Knowing about the hazard for 45 minutes without action is a clear breach causing her injury.",
    eli5: "The shop knew the floor was dangerous and did nothing. That's like knowing your dog bites and letting it loose — you're responsible.",
    category: "tort", difficulty: "easy", rarity: "common",
    principle: "Occupier's liability — duty of care to visitors",
  },
  // ─── MEDIUM CONTRACT ─────────────────────────────────────────────────────────
  {
    id: "c004",
    title: "The Digital Contract",
    facts: "Kezia clicked 'I Agree' on an app's terms of service without reading them. Six months later, the company used her photos for advertising under a clause she had agreed to.",
    question: "Are the terms legally binding?",
    options: ["No, she didn't read them", "Yes, clicking agree forms a valid contract", "Only if terms were sent by post", "No, digital contracts are unenforceable"],
    correctIndex: 1,
    explanation: "Clickwrap agreements are generally enforceable. By clicking 'I Agree', a user accepts the terms.",
    eli5: "Clicking 'agree' is like signing a paper — even if you didn't read it, you still agreed to the deal.",
    category: "contract", difficulty: "medium", rarity: "common",
    principle: "Consensus ad idem — agreement in digital contracts",
  },
  // ─── MEDIUM TORT ─────────────────────────────────────────────────────────────
  {
    id: "c005",
    title: "The Defamatory Post",
    facts: "A politician posted on social media that a restaurant served contaminated food, causing 60% revenue loss. The post was false.",
    question: "What legal action can the restaurant take?",
    options: ["None — it's just an opinion", "Sue for defamation / libel", "Sue for copyright infringement", "Only complain to the platform"],
    correctIndex: 1,
    explanation: "Publishing a false statement of fact causing reputational damage constitutes defamation. Because it was written, it is specifically libel.",
    eli5: "Spreading lies about someone that hurts their business is called defamation — like starting a rumor that destroys someone's reputation.",
    category: "tort", difficulty: "medium", rarity: "rare",
    principle: "Defamation — false statement of fact causing reputational harm",
  },
  // ─── MEDIUM CRIMINAL ─────────────────────────────────────────────────────────
  {
    id: "c006",
    title: "The Forged Signature",
    facts: "Troy signed his elderly mother's name on a property deed transferring her home to himself while she was in hospital.",
    question: "What is the most appropriate charge?",
    options: ["Breach of contract", "Fraud by false representation", "Trespass to goods", "Conversion only"],
    correctIndex: 1,
    explanation: "Forging a signature on a legal document to gain property constitutes fraud by false representation — a serious criminal offence.",
    eli5: "Pretending to be someone else to steal their house is fraud — using a lie to take something valuable.",
    category: "criminal", difficulty: "medium", rarity: "rare",
    principle: "Fraud by false representation — dishonest deception for gain",
  },
  // ─── HARD CONTRACT ───────────────────────────────────────────────────────────
  {
    id: "c007",
    title: "The Broken Exclusion Clause",
    facts: "A parking company's sign said 'No liability for damage to vehicles.' A customer's car was deliberately scratched by an attendant.",
    question: "Is the exclusion clause enforceable?",
    options: ["Yes, the sign was clearly visible", "No, you cannot exclude liability for deliberate acts", "Only if it was on the ticket too", "Yes, always enforceable in contract"],
    correctIndex: 1,
    explanation: "Exclusion clauses cannot protect against deliberate wrongdoing by an employee. Such clauses are void in these circumstances.",
    eli5: "You can put up any sign you want, but you can't use it to escape blame for something your employee deliberately did.",
    category: "contract", difficulty: "hard", rarity: "rare",
    principle: "Exclusion clauses — cannot exclude liability for deliberate harm",
  },
  // ─── HARD CONTRACT ───────────────────────────────────────────────────────────
  {
    id: "c008",
    title: "The Corporate Veil",
    facts: "A director set up a company solely to enter contracts knowing it would default, while personally retaining all profits offshore. Creditors are left unpaid.",
    question: "Can creditors sue the director personally?",
    options: ["No, the company is a separate legal entity", "Yes — the court can pierce the corporate veil for fraud", "Only in criminal court", "No, directors have absolute immunity"],
    correctIndex: 1,
    explanation: "Courts will pierce the corporate veil where the company is used as a device to commit fraud or evade legal obligations.",
    eli5: "Normally a company protects you personally — but if you set up a fake company just to steal money, the court will see right through it.",
    category: "contract", difficulty: "hard", rarity: "legendary",
    principle: "Piercing the corporate veil — fraud exception to separate legal personality",
  },
  // ─── HARD TORT ───────────────────────────────────────────────────────────────
  {
    id: "c009",
    title: "The Voluntary Rescue",
    facts: "An off-duty paramedic assisted at a car accident. During treatment he made an error worsening the victim's condition. The victim sued him.",
    question: "Is the paramedic liable?",
    options: ["Yes, he caused additional harm", "Depends on whether he acted reasonably in the circumstances", "No, good samaritans have absolute immunity", "Yes, he should have called 911 instead"],
    correctIndex: 1,
    explanation: "Good Samaritan laws protect voluntary rescuers from liability unless they acted recklessly. The standard is whether they acted reasonably given the emergency.",
    eli5: "If you choose to help someone in an emergency, the law usually protects you as long as you tried your best.",
    category: "tort", difficulty: "hard", rarity: "legendary",
    principle: "Good Samaritan doctrine — voluntary rescuer liability standard",
  },
  // ─── HARD CRIMINAL ───────────────────────────────────────────────────────────
  {
    id: "c010",
    title: "The Innocent Drug Mule",
    facts: "Camille was asked by her boyfriend to carry a suitcase through customs. She had no knowledge it contained cocaine and was arrested.",
    question: "Is Camille guilty of drug trafficking?",
    options: ["Yes — drugs were in her possession", "No — she lacked the required knowledge (mens rea)", "Yes — ignorance is no defense", "Only if she was paid for it"],
    correctIndex: 1,
    explanation: "Drug trafficking requires both actus reus and mens rea. Without knowledge of the drugs, the mental element is absent.",
    eli5: "Being guilty of a crime means you had to KNOW you were doing something wrong. If you genuinely didn't know, you can't be fully blamed.",
    category: "criminal", difficulty: "hard", rarity: "legendary",
    principle: "Mens rea — guilty mind as a requirement for criminal liability",
  },

  // ─── CONSTITUTIONAL LAW ──────────────────────────────────────────────────────
  {
    id: "c011",
    title: "The COVID Emergency Powers",
    facts: "A government passed emergency regulations banning all public gatherings and worship without parliamentary approval. A church challenged the law.",
    question: "Can emergency powers override constitutional rights?",
    options: ["Yes, always during a health crisis", "Only if proportionate and subject to judicial oversight", "No, never — rights are absolute", "Yes, if the Prime Minister approves"],
    correctIndex: 1,
    explanation: "Emergency powers may temporarily restrict rights but must be proportionate and subject to judicial review. Courts can strike down disproportionate measures.",
    eli5: "Even in emergencies, the government can't do whatever it wants — the courts make sure restrictions aren't too extreme.",
    category: "constitutional", difficulty: "medium", rarity: "rare",
    principle: "Proportionality — emergency powers must be necessary and proportionate",
  },
  {
    id: "c012",
    title: "The Newspaper Leak",
    facts: "A journalist published classified government documents exposing corruption. The government sought an injunction to prevent further publication citing national security.",
    question: "Which right is in conflict here?",
    options: ["Right to privacy vs right to work", "Freedom of expression vs national security", "Right to education vs taxation", "Freedom of assembly vs public order"],
    correctIndex: 1,
    explanation: "The court must balance freedom of the press against national security. Courts apply a proportionality test — suppression must be strictly necessary.",
    eli5: "The right to share information and the government's need for secrets sometimes crash into each other — the court decides who wins this tug of war.",
    category: "constitutional", difficulty: "medium", rarity: "rare",
    principle: "Freedom of expression — press freedom vs national security balancing test",
  },
  {
    id: "c013",
    title: "The Prisoner's Vote",
    facts: "A man sentenced to 4 years in prison challenged a law stripping all convicted prisoners of the right to vote during their sentence.",
    question: "Is a blanket voting ban on prisoners constitutional?",
    options: ["Yes — criminals forfeit all rights", "No — a blanket ban may be disproportionate", "Yes — prison is punishment", "No — prisoners have more rights than free people"],
    correctIndex: 1,
    explanation: "The European Court of Human Rights held that a blanket ban on prisoner voting is disproportionate. Targeted restrictions based on offence type may be permissible.",
    eli5: "Taking away ALL voting rights from every prisoner, no matter what they did, might be too harsh — courts say it depends on the crime.",
    category: "constitutional", difficulty: "hard", rarity: "rare",
    principle: "Proportionality — restrictions on rights must be tailored to their purpose",
  },
  {
    id: "c014",
    title: "Stop and Search Powers",
    facts: "Police were given broad powers to stop and search anyone without suspicion in a designated zone. A civil liberties group challenged the law.",
    question: "What constitutional concern does this raise?",
    options: ["Right to education", "Right to liberty and freedom from discrimination", "Right to property", "Right to work"],
    correctIndex: 1,
    explanation: "Broad stop-and-search powers risk racial profiling and unjustified restriction of liberty. Courts require such powers be proportionate and non-discriminatory.",
    eli5: "The police can't just stop anyone for no reason — that would let them target people unfairly based on how they look.",
    category: "constitutional", difficulty: "medium", rarity: "common",
    principle: "Right to liberty — police powers must be proportionate and non-discriminatory",
  },
  {
    id: "c015",
    title: "The School Prayer",
    facts: "A state school mandated a daily Christian prayer for all students. A Muslim student's family challenged this as a violation of religious freedom.",
    question: "Is mandatory school prayer constitutional?",
    options: ["Yes — the school sets its own rules", "No — it violates freedom of religion", "Only if parents consent", "Yes — Christianity is the official religion"],
    correctIndex: 1,
    explanation: "Mandatory religious observance in state-funded schools violates freedom of religion. The state must remain neutral on religious matters.",
    eli5: "The government can't force you to pray to any religion — that's YOUR choice, not the school's.",
    category: "constitutional", difficulty: "easy", rarity: "common",
    principle: "Freedom of religion — state neutrality in religious matters",
  },
  {
    id: "c016",
    title: "The Mandatory Death Penalty",
    facts: "Under a Caribbean country's law, any conviction for drug trafficking automatically carried the death penalty with no judicial discretion allowed.",
    question: "Is a mandatory death sentence constitutional?",
    options: ["Yes — it deters crime effectively", "No — it may violate the right to life and due process", "Yes — parliament decided it", "No — only elected officials can impose death"],
    correctIndex: 1,
    explanation: "The Privy Council has held that mandatory death sentences are unconstitutional as they prevent courts from considering individual circumstances, violating the right to life.",
    eli5: "A judge needs to be able to look at ALL the facts before sentencing someone to death — having no choice is against the rules of fairness.",
    category: "constitutional", difficulty: "hard", rarity: "legendary",
    principle: "Right to life — mandatory death sentences deny individual justice",
  },
  {
    id: "c017",
    title: "The Equal Pay Challenge",
    facts: "Female nurses at a hospital were paid 20% less than male technicians doing work of equal value. The nurses brought a constitutional challenge.",
    question: "What constitutional right is engaged?",
    options: ["Right to health care", "Right to equality and non-discrimination", "Right to form a union", "Freedom of movement"],
    correctIndex: 1,
    explanation: "Equal pay for equal work is a fundamental right protected by most constitutions' equality provisions. Gender-based pay discrimination is unconstitutional.",
    eli5: "If you and a friend do the same job, you should both get paid the same — it doesn't matter if one is a boy or a girl.",
    category: "constitutional", difficulty: "easy", rarity: "common",
    principle: "Equality — non-discrimination in remuneration",
  },
  {
    id: "c018",
    title: "The Surveillance State",
    facts: "A government secretly collected all citizens' phone metadata without a warrant. A civil society group discovered this and challenged it in court.",
    question: "What right does mass surveillance potentially violate?",
    options: ["Right to free education", "Right to privacy and freedom from arbitrary interference", "Right to work", "Freedom of movement"],
    correctIndex: 1,
    explanation: "Mass surveillance without judicial oversight violates the right to privacy. States must show necessity and proportionality for any surveillance program.",
    eli5: "The government can't secretly read all your texts and listen to all your calls without a very good reason and a judge's permission.",
    category: "constitutional", difficulty: "medium", rarity: "rare",
    principle: "Right to privacy — mass surveillance requires judicial oversight",
  },
  {
    id: "c019",
    title: "The Banned Protest",
    facts: "The government banned a planned protest march citing traffic disruption. Organizers argued the ban was an unlawful restriction on their freedom of assembly.",
    question: "Can the government ban a lawful protest?",
    options: ["Yes, if it might cause inconvenience", "Only if there is a clear and imminent threat to public order", "Yes, the government always has this power", "No, protests can never be banned"],
    correctIndex: 1,
    explanation: "Freedom of assembly is a fundamental right. Restrictions must be necessary and proportionate — inconvenience alone does not justify a ban.",
    eli5: "People have the right to march and protest. The government can only stop them if things might actually turn dangerous, not just inconvenient.",
    category: "constitutional", difficulty: "medium", rarity: "common",
    principle: "Freedom of assembly — restrictions must be necessary and proportionate",
  },
  {
    id: "c020",
    title: "The Citizenship Dispute",
    facts: "Maya was born abroad to a Jamaican citizen father. When she applied for citizenship she was denied because her mother was not Jamaican. Her father had the same rights automatically.",
    question: "What constitutional argument does Maya have?",
    options: ["None — citizenship is the government's choice", "Gender discrimination in citizenship laws", "Maya should apply for a visa instead", "Only children born in Jamaica can be citizens"],
    correctIndex: 1,
    explanation: "Differential treatment of citizenship rights based on whether the citizen parent is the mother or father constitutes gender discrimination under equality provisions.",
    eli5: "If a dad can pass on citizenship but a mom can't, that's unfair — the law should treat moms and dads the same way.",
    category: "constitutional", difficulty: "hard", rarity: "rare",
    principle: "Constitutional equality — gender discrimination in citizenship laws",
  },

  // ─── MORE CRIMINAL ────────────────────────────────────────────────────────────
  {
    id: "c021",
    title: "The Deepfake Fraud",
    facts: "A businessman used AI-generated video of a bank CEO authorising a transfer to steal $2 million from the bank's clients.",
    question: "What is the most appropriate charge?",
    options: ["Simple theft", "Fraud by false representation using technology", "Copyright infringement", "Civil trespass"],
    correctIndex: 1,
    explanation: "Using AI-generated fake media to deceive victims into transferring money constitutes fraud by false representation — a serious criminal offence.",
    eli5: "Making a fake video to trick people into giving you money is fraud — it's using a clever lie to steal.",
    category: "criminal", difficulty: "medium", rarity: "rare",
    principle: "Fraud by false representation — technology-enabled deception",
  },
  {
    id: "c022",
    title: "The Stolen Bitcoin",
    facts: "Kyle hacked into a cryptocurrency exchange and transferred 50 Bitcoin to his own wallet. He argued that digital coins are not 'property' and cannot be stolen.",
    question: "Can cryptocurrency be the subject of theft?",
    options: ["No — it's not physical property", "Yes — courts treat cryptocurrency as property", "Only if it has been printed out", "No — only cash can be stolen"],
    correctIndex: 1,
    explanation: "Courts in multiple jurisdictions now recognise cryptocurrency as property capable of being stolen. Kyle's argument has been repeatedly rejected.",
    eli5: "Just because you can't hold Bitcoin in your hand doesn't mean it isn't yours — courts say digital money is still money.",
    category: "criminal", difficulty: "medium", rarity: "rare",
    principle: "Definition of property — cryptocurrency as theft subject matter",
  },
  {
    id: "c023",
    title: "The Revenge Photos",
    facts: "After a breakup, Leon posted intimate photos of his ex-girlfriend online without her consent to embarrass her. She reported him to police.",
    question: "What criminal offence has Leon committed?",
    options: ["None — he can post what he owns", "Disclosure of private sexual images without consent", "Breach of copyright", "Harassment only"],
    correctIndex: 1,
    explanation: "Posting intimate images without consent ('revenge porn') is a criminal offence in most jurisdictions, carrying significant sentences.",
    eli5: "Sharing private photos of someone without their permission to hurt them is a crime — it's a serious invasion of their privacy.",
    category: "criminal", difficulty: "easy", rarity: "common",
    principle: "Non-consensual intimate image disclosure — criminal liability",
  },
  {
    id: "c024",
    title: "The Drunk Defense",
    facts: "Jordan, severely intoxicated after drinking for hours, got into a fight and seriously injured someone. His lawyer argued he was too drunk to form criminal intent.",
    question: "Can severe intoxication be a complete defense to assault?",
    options: ["Yes — he didn't know what he was doing", "No — voluntary intoxication is rarely a complete defense", "Yes if blood alcohol is above 0.2", "No — only drugs provide this defense"],
    correctIndex: 1,
    explanation: "Voluntary intoxication is generally not a complete defense. Courts hold that a person who chose to drink cannot fully escape responsibility for crimes committed while drunk.",
    eli5: "If you choose to drink so much you don't know what you're doing, the law says that's still your fault — you made the choice to drink.",
    category: "criminal", difficulty: "medium", rarity: "common",
    principle: "Voluntary intoxication — not a complete defense to basic intent crimes",
  },
  {
    id: "c025",
    title: "The Road Rage Killing",
    facts: "After being cut off in traffic, Patrick deliberately drove his car at the other driver and killed him. Patrick claimed he just wanted to scare him.",
    question: "What is the likely charge?",
    options: ["Careless driving", "Murder — intentional killing with malice aforethought", "Manslaughter only", "Death by dangerous driving"],
    correctIndex: 1,
    explanation: "Deliberately driving a vehicle at a person with intent to kill or cause grievous bodily harm constitutes murder, regardless of claims about intent to 'only scare'.",
    eli5: "Driving your car at someone on purpose to hurt them is just as much murder as using any other weapon.",
    category: "criminal", difficulty: "hard", rarity: "rare",
    principle: "Murder — intention to kill or cause grievous bodily harm",
  },
  {
    id: "c026",
    title: "The Cyberstalker",
    facts: "For six months, Damien sent his ex-partner 200+ unwanted messages per day, created fake profiles impersonating her, and appeared outside her workplace despite requests to stop.",
    question: "What charge applies?",
    options: ["No offence — he didn't touch her", "Cyberstalking and harassment", "Trespass only", "Breach of peace only"],
    correctIndex: 1,
    explanation: "Persistent unwanted digital contact causing fear constitutes stalking/cyberstalking — a serious criminal offence in most jurisdictions.",
    eli5: "Bombarding someone with messages when they've told you to stop is a crime — it doesn't have to be physical to cause real fear and harm.",
    category: "criminal", difficulty: "easy", rarity: "common",
    principle: "Cyberstalking — repeated digital contact causing fear",
  },
  {
    id: "c027",
    title: "The Ponzi Scheme",
    facts: "Roderick convinced 200 investors to put money into a fake 'guaranteed return' fund. He paid early investors using later investors' money until the scheme collapsed.",
    question: "What is the primary charge?",
    options: ["Breach of contract only", "Fraud and obtaining property by deception", "Tax evasion", "Negligent misrepresentation"],
    correctIndex: 1,
    explanation: "A Ponzi scheme involves systematic fraud — creating false representations about investment returns to obtain money from victims.",
    eli5: "Promising people their money will grow when you're actually just using new investors' money to pay old ones is a big fraud crime.",
    category: "criminal", difficulty: "medium", rarity: "rare",
    principle: "Fraud — systematic deception to obtain financial gain",
  },
  {
    id: "c028",
    title: "The TikTok Driver",
    facts: "A 19-year-old influencer was recording a TikTok video while driving at 70mph. She swerved, hit a cyclist who died, and continued filming. She claimed she didn't realise what had happened.",
    question: "What is the most serious possible charge?",
    options: ["Careless driving", "Causing death by dangerous driving", "Manslaughter only", "Failure to stop after accident"],
    correctIndex: 1,
    explanation: "Recording video while driving at high speed, causing death, constitutes causing death by dangerous driving — a serious criminal offence.",
    eli5: "Driving fast while making videos on your phone and killing someone because of it is a very serious crime, even if it was an accident.",
    category: "criminal", difficulty: "easy", rarity: "common",
    principle: "Dangerous driving — criminal liability for phone use causing death",
  },

  // ─── MORE CONTRACT ────────────────────────────────────────────────────────────
  {
    id: "c029",
    title: "The Influencer No-Show",
    facts: "A company paid Tara $15,000 upfront to post promotional content over 3 months. After receiving payment, she posted once then disappeared. The company sued.",
    question: "What remedy does the company have?",
    options: ["None — she posted once as agreed", "Repayment of money and damages for breach of contract", "Only a replacement influencer", "Only damages, not repayment"],
    correctIndex: 1,
    explanation: "Tara committed a material breach of contract. The company can recover the advance payment and damages for losses caused by the breach.",
    eli5: "She took the money and didn't do the job — that's breaking a deal, and she has to give back the money and pay for the problems she caused.",
    category: "contract", difficulty: "easy", rarity: "common",
    principle: "Breach of contract — remedy of damages and restitution",
  },
  {
    id: "c030",
    title: "The Verbal Lease",
    facts: "Simone and her landlord verbally agreed on a 3-year lease. Six months in, the landlord sold the house without telling her. The new owner wants her out.",
    question: "Can Simone enforce the verbal lease?",
    options: ["Yes — a deal is a deal", "Probably not — leases for over one year must be in writing", "Yes — verbal agreements always bind", "No — she can't prove it"],
    correctIndex: 1,
    explanation: "Under the Statute of Frauds, leases exceeding one year must be evidenced in writing to be enforceable. A verbal 3-year lease may be unenforceable.",
    eli5: "Some deals are too important to be just a handshake — long-term leases need to be written down to count in court.",
    category: "contract", difficulty: "medium", rarity: "common",
    principle: "Statute of Frauds — written requirement for leases over one year",
  },
  {
    id: "c031",
    title: "The COVID Wedding",
    facts: "A couple booked a $25,000 venue for their wedding. Government COVID lockdown made the event legally impossible to hold. The venue refused to refund.",
    question: "What legal doctrine might assist the couple?",
    options: ["Breach of contract by the couple", "Frustration — a supervening event made performance impossible", "The venue is always right", "Force majeure doesn't exist"],
    correctIndex: 1,
    explanation: "The doctrine of frustration discharges a contract where an unforeseen event makes performance impossible. Government lockdown can constitute frustration.",
    eli5: "If something totally unexpected and impossible to control stops your deal from happening, the law lets both sides out of the agreement.",
    category: "contract", difficulty: "medium", rarity: "rare",
    principle: "Frustration — supervening impossibility discharges contract",
  },
  {
    id: "c032",
    title: "The Misrepresented Car",
    facts: "A car dealer told Marco the car had 30,000 miles. It had 90,000. Marco signed a contract with a clause saying 'buyer accepts vehicle as is.' He later discovered the truth.",
    question: "Can Marco rescind the contract?",
    options: ["No — he signed 'as is'", "Yes — a fraudulent misrepresentation overrides an 'as is' clause", "Only if he gets a mechanic report", "No — the mileage doesn't matter legally"],
    correctIndex: 1,
    explanation: "Fraudulent misrepresentation gives the victim the right to rescind a contract, even where an 'as is' clause exists. You cannot contract out of your own fraud.",
    eli5: "Even if you sign a paper saying you accept it as is, if the seller LIED to make you sign, that lie wins over the paper.",
    category: "contract", difficulty: "hard", rarity: "rare",
    principle: "Misrepresentation — fraudulent misrepresentation overrides exemption clauses",
  },
  {
    id: "c033",
    title: "The Non-Compete Clause",
    facts: "A senior employee left a firm and started a competing business serving the same clients. His contract had a clause preventing him from competing for 5 years in any country.",
    question: "Is the non-compete clause enforceable?",
    options: ["Yes — he signed it", "Only if it is reasonable in scope, time, and geography", "No — you can always compete freely", "Yes — for exactly 5 years as agreed"],
    correctIndex: 1,
    explanation: "Non-compete clauses must be reasonable in duration and geographic scope to be enforceable. A worldwide 5-year ban is likely unenforceable as a restraint of trade.",
    eli5: "If you promise not to compete with your old boss, that's only fair for a reasonable time and area — you can't be banned from working forever everywhere.",
    category: "contract", difficulty: "hard", rarity: "rare",
    principle: "Restraint of trade — non-compete must be reasonable",
  },
  {
    id: "c034",
    title: "The Cancelled Video Game",
    facts: "Players paid for in-game items in a mobile game. The company shut down the game without warning, making all purchased items worthless.",
    question: "Do players have a legal claim?",
    options: ["No — it's just a game", "Potentially yes — breach of implied terms and consumer protection", "Only if they spent over $1,000", "No — terms of service prevent all claims"],
    correctIndex: 1,
    explanation: "Consumer protection laws may apply where digital purchases are suddenly rendered worthless. Courts increasingly scrutinize terms of service that waive all consumer rights.",
    eli5: "If you paid real money for something and the company takes it away for no reason, you might have a right to get your money back.",
    category: "contract", difficulty: "medium", rarity: "common",
    principle: "Consumer protection — implied terms in digital goods contracts",
  },
  {
    id: "c035",
    title: "The Builder's Lien",
    facts: "A contractor completed a $40,000 renovation but was not paid. He placed a lien on the property before the owner could sell it.",
    question: "Is the contractor entitled to place a lien?",
    options: ["No — that's trespass", "Yes — most jurisdictions allow construction liens for unpaid work", "Only if there is a written contract", "No — liens only apply to banks"],
    correctIndex: 1,
    explanation: "Construction liens (mechanics' liens) allow unpaid contractors to place a legal claim on property they improved, preventing sale until payment is made.",
    eli5: "If you build something on someone's house and they don't pay you, the law lets you put a 'hold' on their house so they can't sell it until they pay.",
    category: "contract", difficulty: "medium", rarity: "common",
    principle: "Construction lien — security for unpaid contractor",
  },

  // ─── MORE TORT ────────────────────────────────────────────────────────────────
  {
    id: "c036",
    title: "The Viral Embarrassment",
    facts: "A restaurant employee secretly filmed a customer having an embarrassing fall and posted it online. It went viral with millions of views. The customer sued.",
    question: "What tort claim does the customer have?",
    options: ["None — it happened in public", "Invasion of privacy / misuse of private information", "Theft of likeness", "Copyright infringement only"],
    correctIndex: 1,
    explanation: "Even in semi-public places, individuals have a reasonable expectation of privacy. Publishing footage for entertainment without consent may give rise to a privacy claim.",
    eli5: "Just because something happens where other people can see doesn't mean someone can film it and share it online to embarrass you.",
    category: "tort", difficulty: "medium", rarity: "common",
    principle: "Privacy — reasonable expectation of privacy in semi-public places",
  },
  {
    id: "c037",
    title: "The First Dog Bite",
    facts: "Fido, a normally gentle dog, bit a visitor at his owner's home for the first time. The visitor required surgery and sued the owner.",
    question: "Is the owner liable for a first-time bite?",
    options: ["No — it was the first time, owner had no warning", "It depends on jurisdiction — some apply strict liability, others require prior knowledge", "Yes always — pets are always owner's risk", "No — dogs are allowed one free bite everywhere"],
    correctIndex: 1,
    explanation: "Some jurisdictions apply strict liability for dog bites; others follow the 'one bite rule' requiring prior knowledge of viciousness. The answer varies by location.",
    eli5: "Different places have different rules about dog bites — in some places you're always responsible for your dog, in others only if you knew it was dangerous.",
    category: "tort", difficulty: "hard", rarity: "rare",
    principle: "Strict liability vs negligence — dog bite rules vary by jurisdiction",
  },
  {
    id: "c038",
    title: "The Noisy Neighbour",
    facts: "For 18 months, a neighbour's late-night parties caused sleep deprivation and health issues. Complaints to the council were ignored. The victim sued.",
    question: "What tort applies?",
    options: ["Trespass to land", "Private nuisance — unreasonable interference with use of land", "Defamation", "Negligence only"],
    correctIndex: 1,
    explanation: "Private nuisance covers unreasonable interference with a person's use and enjoyment of their land. Persistent loud noise over 18 months clearly qualifies.",
    eli5: "If your neighbour's noise is so bad it makes your life miserable, the law calls it a 'nuisance' and they have to stop.",
    category: "tort", difficulty: "easy", rarity: "common",
    principle: "Private nuisance — unreasonable interference with quiet enjoyment",
  },
  {
    id: "c039",
    title: "The Wrong Leg",
    facts: "A surgeon operated on a patient's left knee when it was the right that needed treatment. The mistake was discovered post-surgery. The patient suffered additional pain and recovery time.",
    question: "What is the basis of the patient's claim?",
    options: ["Trespass only", "Medical negligence — breach of duty of care", "Assault and battery", "Breach of statutory duty"],
    correctIndex: 1,
    explanation: "Operating on the wrong body part constitutes medical negligence (and potentially battery). The surgeon breached the duty of care owed to the patient.",
    eli5: "A doctor who operates on the wrong part of your body made a serious mistake — they had a responsibility to get it right, and they didn't.",
    category: "tort", difficulty: "easy", rarity: "common",
    principle: "Medical negligence — breach of duty of care by healthcare professional",
  },
  {
    id: "c040",
    title: "The Exploding Phone",
    facts: "A phone with a defective battery caught fire while charging normally, badly burning the user's hand. The manufacturer knew about similar incidents from other customers.",
    question: "What legal theory supports the user's claim?",
    options: ["None — products sometimes fail", "Product liability — manufacturer responsible for defective products", "Contract only with the retailer", "Negligence only if the user modified the phone"],
    correctIndex: 1,
    explanation: "Under product liability, manufacturers are responsible for defective products causing injury. The fact they knew of similar incidents strengthens the case.",
    eli5: "If a company makes something dangerous and it hurts you, they have to pay — especially if they already knew it was a problem.",
    category: "tort", difficulty: "medium", rarity: "common",
    principle: "Product liability — manufacturer's responsibility for defective goods",
  },
  {
    id: "c041",
    title: "The School Bully",
    facts: "A 13-year-old was bullied for months by a classmate. The school had received three written complaints from parents and took no action. The victim suffered psychological harm.",
    question: "Can the school be held liable?",
    options: ["No — children will be children", "Yes — the school breached its duty of care after receiving clear warnings", "Only if the bullying was physical", "No — only the bully's parents are liable"],
    correctIndex: 1,
    explanation: "Schools owe students a duty of care. After receiving multiple complaints, the school's failure to act constitutes a breach. Foreseeability of harm is clear.",
    eli5: "When a school is told again and again that a child is being hurt and they do nothing, the school becomes responsible for what happens.",
    category: "tort", difficulty: "medium", rarity: "common",
    principle: "Duty of care — schools liable for foreseeable harm after notice",
  },

  // ─── FUN / WEIRD CASES ────────────────────────────────────────────────────────
  {
    id: "c042",
    title: "Liebeck v McDonald's (The Hot Coffee Case)",
    facts: "In 1994, Stella Liebeck spilled McDonald's coffee on herself and suffered third-degree burns. McDonald's had received 700+ prior burn complaints. She sued and won.",
    question: "Why did the jury award her over $2 million?",
    options: ["Coffee should always be free", "McDonald's knew their coffee was dangerously hot but ignored complaints", "She sued for emotional distress alone", "The court pitied her"],
    correctIndex: 1,
    explanation: "McDonald's served coffee at 180-190°F — far hotter than home brewing. Despite 700+ prior complaints, they made no changes. The jury found their conduct reckless.",
    eli5: "McDonald's knew their coffee was dangerously hot and kept ignoring people getting hurt. The court said that's not okay.",
    category: "tort", difficulty: "easy", rarity: "rare",
    principle: "Product liability — actual knowledge of danger creates heightened duty",
  },
  {
    id: "c043",
    title: "The Haunted House",
    facts: "A buyer purchased a historic home. After closing, she discovered the seller had widely promoted the house as haunted (there were newspaper articles). She sought to rescind the contract.",
    question: "Did the seller have a duty to disclose the 'haunting'?",
    options: ["No — ghosts aren't real so it's irrelevant", "Yes — material facts known to affect buyer's decision must be disclosed", "Only if asked directly", "No — buyers should investigate"],
    correctIndex: 1,
    explanation: "In Stambovsky v Ackley (1991), a NY court held that since the seller created the ghost reputation, they were bound to disclose it as a material fact affecting value.",
    eli5: "If the seller told everyone their house was haunted, they can't pretend they didn't when selling it — buyers have a right to know!",
    category: "contract", difficulty: "hard", rarity: "legendary",
    principle: "Caveat emptor — sellers must disclose known material facts they created",
  },
  {
    id: "c044",
    title: "The Missing Comma",
    facts: "A contract stated a service would run 'every day except Sunday and holidays, Monday, Tuesday, Wednesday, Thursday and Friday.' A missing comma cost a company $10 million.",
    question: "What legal principle does this illustrate?",
    options: ["Contracts don't need to be clear", "Precise drafting is essential — ambiguity is construed against the drafter", "Only lawyers can write contracts", "The company waived their claim"],
    correctIndex: 1,
    explanation: "The Oxford comma case (2018, US) showed how missing punctuation can change the meaning of a contract entirely, costing a business millions in overtime pay.",
    eli5: "A tiny missing comma in a contract made the whole thing mean something different — grammar really does matter in law!",
    category: "contract", difficulty: "medium", rarity: "legendary",
    principle: "Contra proferentem — ambiguity construed against the drafter",
  },
  {
    id: "c045",
    title: "The Virtual Property Theft",
    facts: "A player spent $85,000 on a virtual space station in an online game. Another player used an exploit to steal it. The victim sued the game developer for failing to prevent the theft.",
    question: "Can virtual property be the subject of legal claims?",
    options: ["No — it's just a game", "Yes — courts in some countries have ruled virtual property has real value", "Only for amounts over $1 million", "No — only physical items count"],
    correctIndex: 1,
    explanation: "Chinese and Dutch courts have held virtual property can have real legal value. Game developers may have obligations to protect players' virtual assets.",
    eli5: "If you pay real money for something virtual, some courts say it's real enough to protect — especially when that 'something' cost $85,000!",
    category: "tort", difficulty: "hard", rarity: "legendary",
    principle: "Emerging law — virtual property and developer obligations",
  },
  {
    id: "c046",
    title: "The Winning Lottery Ticket",
    facts: "Bob and Sarah agreed to split lottery winnings if either won. Bob won $5 million and refused to share. Sarah had only a verbal agreement.",
    question: "Can Sarah enforce the agreement?",
    options: ["No — verbal agreements about lottery are unenforceable", "Likely yes — verbal agreements about sharing lottery winnings have been enforced", "Only if she also bought tickets", "No — Bob owns the ticket"],
    correctIndex: 1,
    explanation: "Courts have frequently enforced oral lottery-sharing agreements. The key elements are: offer, acceptance and consideration. Sarah's promise to share in return for splitting winnings may suffice.",
    eli5: "A promise to share lottery money counts as a deal — even if it wasn't written down. Bob may have to share!",
    category: "contract", difficulty: "medium", rarity: "rare",
    principle: "Oral agreements — lottery-sharing contracts may be enforceable",
  },
  {
    id: "c047",
    title: "The Wrong Wedding Cake",
    facts: "A bakery delivered a chocolate cake instead of the agreed vanilla for a wedding. The couple sued for ruined wedding photos and emotional distress.",
    question: "What damages can the couple claim?",
    options: ["Nothing — it's just cake", "Direct loss (cake cost) and potentially consequential damages", "Unlimited damages for any distress", "Only the cost of the cake"],
    correctIndex: 1,
    explanation: "The couple can claim the cost of the wrong cake (direct loss). Consequential damages (ruined wedding) depend on whether they were reasonably foreseeable when contracting.",
    eli5: "You can get money back for the wrong cake and maybe extra money if the wrong cake caused other problems the baker knew about.",
    category: "contract", difficulty: "medium", rarity: "common",
    principle: "Consequential damages — losses must be foreseeable at time of contracting",
  },
  {
    id: "c048",
    title: "The NFT Scam",
    facts: "An artist sold an NFT claiming it gave the buyer ownership of a famous artwork. The artist had no rights to the artwork. The buyer paid $400,000 and later discovered the fraud.",
    question: "What legal claims arise?",
    options: ["None — NFTs are experimental", "Fraud, unjust enrichment, and potentially criminal charges", "Only intellectual property claims", "Only contract damages"],
    correctIndex: 1,
    explanation: "Selling an NFT purporting to grant rights the seller doesn't have constitutes fraud. Criminal charges, civil damages, and restitution claims all arise.",
    eli5: "Selling someone a 'deed' to something you don't own is fraud — it doesn't matter if the deed is an NFT or a piece of paper.",
    category: "criminal", difficulty: "medium", rarity: "rare",
    principle: "NFT fraud — misrepresentation of digital asset ownership",
  },
  {
    id: "c049",
    title: "The Vaccine Dismissal",
    facts: "A hospital employee refused mandatory COVID vaccination on grounds of personal belief (not religious or medical). The hospital dismissed her. She claimed unfair dismissal.",
    question: "Was the dismissal lawful?",
    options: ["No — personal belief is protected", "Likely yes — mandatory vaccination for healthcare workers can be lawfully required", "Only if the hospital offered alternatives", "No — vaccination is always a personal choice"],
    correctIndex: 1,
    explanation: "Courts have generally held that healthcare employers can lawfully mandate vaccination to protect vulnerable patients, making dismissal for refusal fair.",
    eli5: "A hospital can require nurses to be vaccinated to protect sick patients — it's not just about the nurse's own choice.",
    category: "constitutional", difficulty: "hard", rarity: "rare",
    principle: "Mandatory vaccination — balancing employee rights with public health duties",
  },
  {
    id: "c050",
    title: "The Drone Photographer",
    facts: "James used a drone to photograph a celebrity's private garden and sold the photos to a magazine. The celebrity's garden was not visible from the street.",
    question: "What legal claim does the celebrity have?",
    options: ["None — airspace is public", "Invasion of privacy — reasonable expectation of privacy in private garden", "Trespass to land only", "Copyright — the celebrity owns the view"],
    correctIndex: 1,
    explanation: "Flying a drone to photograph a private space the celebrity reasonably expected to be private constitutes an invasion of privacy, even if conducted from public airspace.",
    eli5: "Just because you can fly over someone's garden doesn't mean you can take pictures of their private life — they have a right to privacy even outside.",
    category: "tort", difficulty: "medium", rarity: "common",
    principle: "Privacy — reasonable expectation of privacy in enclosed outdoor spaces",
  },
  {
    id: "c051",
    title: "The AI Art Copyright",
    facts: "An artist used AI to generate 100 artworks and tried to register copyright in them. The Copyright Office denied registration, saying the works lacked human authorship.",
    question: "Can AI-generated art be copyrighted?",
    options: ["Yes — whoever runs the AI owns the copyright", "Not without human creative input — authorship requires a human", "Yes — copyright applies to all images", "No — no artwork has copyright anymore"],
    correctIndex: 1,
    explanation: "The US Copyright Office and courts have held that copyright requires human authorship. Pure AI-generated works without human creative selection are not copyrightable.",
    eli5: "To own a copyright, a human has to have actually made creative choices — if a computer does all the creating, nobody owns the result.",
    category: "constitutional", difficulty: "hard", rarity: "legendary",
    principle: "Copyright — human authorship requirement for protection",
  },
  {
    id: "c052",
    title: "The Pandemic Eviction",
    facts: "A tenant couldn't pay rent for 4 months due to government-ordered business closure during COVID. The landlord sought immediate eviction under the contract.",
    question: "What protection might the tenant have?",
    options: ["None — rent must be paid regardless", "Government moratoriums and frustration doctrine may protect the tenant", "Eviction can proceed after 1 month", "The tenant must find a new job immediately"],
    correctIndex: 1,
    explanation: "During COVID, many governments imposed eviction moratoriums. Additionally, frustration or force majeure arguments may apply where a government order prevented earning income.",
    eli5: "When the government tells you to close your business, it's unfair to evict you immediately for not paying rent — many laws protect people in this situation.",
    category: "contract", difficulty: "medium", rarity: "common",
    principle: "Force majeure — government orders may excuse non-performance",
  },
  {
    id: "c053",
    title: "The Social Media Minor",
    facts: "A 12-year-old accessed an adult social media platform by falsely claiming to be 18. She developed anxiety and depression linked to the content. Parents sued the platform.",
    question: "Could the platform be liable?",
    options: ["No — the child lied about her age", "Potentially yes — platforms have duties to implement age verification", "Only if they knew she was 12", "No — parents should monitor children"],
    correctIndex: 1,
    explanation: "Online platforms increasingly face liability for failing to implement adequate age verification systems, even when users lie about age, under child safety laws.",
    eli5: "Just saying 'you must be 18' isn't enough — platforms that have harmful content need to actually check ages properly.",
    category: "tort", difficulty: "hard", rarity: "rare",
    principle: "Platform liability — duty to implement age verification for harmful content",
  },
  {
    id: "c054",
    title: "The Crypto Divorce",
    facts: "During divorce proceedings, a husband claimed he had no valuable assets. His wife's lawyer discovered he had hidden $3 million in cryptocurrency using multiple wallets.",
    question: "What are the legal consequences of hiding crypto assets?",
    options: ["None — crypto is private", "Contempt of court and the court may award the wife a larger share", "The crypto automatically belongs to him", "Only a fine applies"],
    correctIndex: 1,
    explanation: "Hiding assets during divorce is contempt of court. Courts can impose penalties and often award the deceived spouse a larger share of the discovered assets.",
    eli5: "You can't hide money in crypto to cheat your spouse in a divorce — the court can punish you and give your spouse even more of what you hid.",
    category: "criminal", difficulty: "medium", rarity: "rare",
    principle: "Contempt of court — hiding assets in divorce proceedings",
  },
  {
    id: "c055",
    title: "The Whistleblower's Dilemma",
    facts: "A civil servant leaked documents proving the government had secretly been spying on journalists. He was prosecuted under the Official Secrets Act. He claimed public interest as a defense.",
    question: "Can public interest justify leaking official secrets?",
    options: ["Yes — always", "Sometimes, but it is a very narrow exception and rarely succeeds", "Yes if a newspaper publishes it", "No — official secrets can never be revealed"],
    correctIndex: 1,
    explanation: "The public interest defense in official secrets cases is extremely narrow. The disclosure must be genuinely necessary and the defendant must have tried proper channels first.",
    eli5: "Telling the world about government wrongdoing can sometimes be legal, but only if there was a really serious crime and no other way to reveal it.",
    category: "criminal", difficulty: "hard", rarity: "legendary",
    principle: "Whistleblower protection — narrow public interest defense to secrecy offences",
  },
];

export const LEGAL_FACTS = [
  "In the UK, you can be fined for letting your dog bark excessively at night under noise nuisance laws.",
  "A contract made under duress is voidable — the victim can choose to enforce or rescind it.",
  "In Roman law, 'actio de effusis vel deiectis' allowed you to sue someone who threw something from their window and hit you.",
  "The oldest written legal code is the Code of Ur-Nammu from Mesopotamia, dating to around 2100 BC.",
  "In Scotland, you need corroboration — two independent pieces of evidence — to convict someone of a crime.",
  "The presumption of innocence dates back to Roman law: 'ei incumbit probatio qui dicit, non qui negat.'",
  "A 'chocolate cake contract' can be legally binding — as long as there is offer, acceptance and consideration.",
  "In Barbados, the court system still uses procedures derived from English common law established in 1652.",
  "In St. Vincent, legal proceedings can be appealed all the way to the Caribbean Court of Justice.",
  "The Privy Council in London still serves as the final appeal court for several Caribbean nations.",
  "Under CARICOM law, certain trade disputes go to a regional tribunal rather than national courts.",
  "A verbal contract is generally enforceable — except for contracts involving land, marriage, or guarantees.",
  "The doctrine of 'promissory estoppel' means you can sometimes be held to a promise even without consideration.",
  "Grenada achieved independence in 1974, and its constitution remains one of the strongest in the Caribbean.",
  "The concept of 'innocent until proven guilty' did not apply in English courts until the 18th century.",
  "Jamaica's Supreme Court was established in 1879 and sits in Kingston, with circuits across the island.",
  "The House of Lords ceased to be the UK's highest court in 2009 when the UK Supreme Court was created.",
  "In Guyana, the law is a blend of common law and Roman-Dutch law, a colonial legacy of Dutch rule.",
  "The Caribbean Court of Justice, based in Trinidad, serves as an alternative final court to the Privy Council.",
  "The UK Human Rights Act 1998 incorporates the European Convention on Human Rights into domestic law.",
  "Courts in Japan rarely acquit defendants — the conviction rate in Japanese courts is over 99%.",
  "The US Constitution's 4th Amendment protects against unreasonable searches without a warrant.",
  "Constitutional law cases in the Caribbean often reach the Privy Council in London for final determination.",
  "The doctrine of judicial precedent means that higher court decisions bind lower courts in the same system.",
  "In civil law, you only need to prove your case 'on the balance of probabilities' — more likely than not.",
  "In criminal law, the prosecution must prove guilt 'beyond reasonable doubt' — a much higher standard.",
  "Guyana has a unique legal system influenced by British, Dutch, and indigenous Caribbean traditions.",
  "The first written constitution was the Constitution of San Marino, drafted in 1600.",
  "St. Kitts and Nevis has the world's smallest federation, with its own unique constitutional structure.",
  "In Jamaica, 'duppy' (ghost) stories have occasionally been raised in property dispute court cases.",
];

export const RANDOM_EVENTS = [
  { id: "e1", title: "New Evidence Discovered", description: "A witness has come forward. Your next correct answer gives double XP.", icon: "search" },
  { id: "e2", title: "Witness Unavailable", description: "A key witness cannot attend today. You may skip one question at no penalty.", icon: "user-x" },
  { id: "e3", title: "Court Objection!", description: "Opposing counsel objects! Answer the next question within 20 seconds.", icon: "alert-triangle" },
  { id: "e4", title: "Expert Testimony", description: "An expert provides context. 'Explain like I'm 5' is free this question.", icon: "book-open" },
  { id: "e5", title: "Judge's Warning", description: "The judge warns both parties. Credibility score frozen for 2 questions.", icon: "gavel" },
];

export function getRandomCase(exclude?: string[]): LegalCase {
  const available = STATIC_CASES.filter(c => !exclude?.includes(c.id));
  const pool = available.length > 0 ? available : STATIC_CASES;
  return pool[Math.floor(Math.random() * pool.length)];
}

export function getDailyCase(): LegalCase {
  const today = new Date();
  const dayIndex = Math.floor(today.getTime() / 86400000) % STATIC_CASES.length;
  return STATIC_CASES[dayIndex];
}
